PAUSE
CLS
@ECHO OFF
python -m venv venv
ECHO VIRTUAL ENVIRONMENT 'VENV' CREATED
CALL venv\Scripts\activate.bat
ECHO VIRTUAL ENVIRONMENT 'VENV' ACTIVATED
python -m pip install --upgrade pip
ECHO PIP PACKAGE INSTALLATION MANAGER UPGRADED
pip install -r requirements.txt
ECHO FETCHING AND INSTALLING REQUIRED PYTHON PACKAGES FOR OPERATION
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
ECHO FETCHING AND INSTALLING REQUIRED PYTHON PACKAGES FOR BUILDING/FREEZING
python getpywin32.py
ECHO PYWIN32-227 DOWNLOADED
easy_install pywin32-227.exe
ECHO PYWIN32-227 INSTALLED
DEL pywin32-227.exe
ECHO PYWIN32-227 CLEANED UP
PAUSE
